-- Migration: 010_create_brand_campaigns.sql
-- Creates brand campaigns, presets, and campaign assets tables

-- BRAND CAMPAIGNS
CREATE TABLE IF NOT EXISTS brand_campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    prompt TEXT,
    status VARCHAR(50) DEFAULT 'draft',
    banner_key VARCHAR(500),
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    settings JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_brand_campaigns_brand_id ON brand_campaigns(brand_id);
CREATE INDEX idx_brand_campaigns_status ON brand_campaigns(status);

-- BRAND PRESETS
CREATE TABLE IF NOT EXISTS brand_presets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    prompt_template TEXT,
    thumbnail_key VARCHAR(500),
    cost_credits INTEGER DEFAULT 0,
    category VARCHAR(100),
    is_active BOOLEAN DEFAULT true,
    settings JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_brand_presets_brand_id ON brand_presets(brand_id);
CREATE INDEX idx_brand_presets_category ON brand_presets(category);

-- CAMPAIGN ASSETS (generated by workers)
CREATE TABLE IF NOT EXISTS campaign_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID REFERENCES brand_campaigns(id) ON DELETE CASCADE,
    brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
    job_id UUID,
    asset_key VARCHAR(500),
    asset_type VARCHAR(50),
    status VARCHAR(50) DEFAULT 'pending',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_campaign_assets_campaign_id ON campaign_assets(campaign_id);
CREATE INDEX idx_campaign_assets_brand_id ON campaign_assets(brand_id);

-- BRAND THEME SETTINGS
ALTER TABLE brands ADD COLUMN IF NOT EXISTS theme JSONB DEFAULT '{"primaryColor": "#6e4ae0", "accentColor": "#00c9b7"}';
ALTER TABLE brands ADD COLUMN IF NOT EXISTS logo_key VARCHAR(500);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS tagline TEXT;

-- Insert default subscription plans if not exists
INSERT INTO subscription_plans (name, tier, monthly_price, monthly_credits, features, is_active) VALUES
    ('Free', 'free', 0, 10, '["basic_tryon", "fun_filters"]', true),
    ('Starter', 'starter', 2900, 100, '["basic_tryon", "fun_filters", "avatar_creation", "brand_presets"]', true),
    ('Professional', 'professional', 7900, 500, '["basic_tryon", "fun_filters", "avatar_creation", "brand_presets", "campaigns", "analytics"]', true),
    ('Enterprise', 'enterprise', NULL, -1, '["all_features", "white_label", "api_access"]', true)
ON CONFLICT DO NOTHING;
