const express = require('express');
const authRoutes = require('./auth.routes');
const wardrobeRoutes = require('./wardrobe.routes');
const recommendationRoutes = require('./recommendation.routes');
const contentRoutes = require('./content.routes');
const weatherRoutes = require('./weather.routes');
const trendsRoutes = require('./trends.routes');
const fashionResearchRoutes = require('./fashionResearch.routes');
const tryonRoutes = require('./tryon.routes');
const aiRoutes = require('./ai.routes');
const imageProcessingRoutes = require('./imageProcessing.routes');
const userPreferenceRoutes = require('./userPreference.routes');
const analyticsRoutes = require('./analytics.routes');
const declutterRoutes = require('./declutter.routes');
const trendPredictionRoutes = require('./trendPrediction.routes');
const sponsorsRoutes = require('./sponsors.routes');
const adminRoutes = require('./admin.routes');
const kiloRoutes = require('./kilo.routes');
const usageRoutes = require('./usage.routes');
const billingRoutes = require('./billing.routes');
const usersRoutes = require('./users.routes');
const jobsRoutes = require('./jobs.routes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/ai', aiRoutes);
router.use('/tryon', tryonRoutes);
router.use('/wardrobe', wardrobeRoutes);
router.use('/recommendations', recommendationRoutes);
router.use('/content', contentRoutes);
router.use('/weather', weatherRoutes);
router.use('/trends', trendsRoutes);
router.use('/fashion', fashionResearchRoutes);
router.use('/image', imageProcessingRoutes);
router.use('/preferences', userPreferenceRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/declutter', declutterRoutes);
router.use('/trend-prediction', trendPredictionRoutes);
router.use('/admin', adminRoutes);
router.use('/kilo', kiloRoutes);
router.use('/usage', usageRoutes);
router.use('/billing', billingRoutes);
router.use('/jobs', jobsRoutes);
router.use('/', sponsorsRoutes);

module.exports = router;
